### ISSUE TITLE
sixteen_step_sequencer/sampler.cpp issue with Adafruit_QSPI_GD25Q

### ISSUE THREAD

**Issue by wurls80** [adafruit/Adafruit_NeoTrellisM4#19]
Hi,
I've tried compiling the sixteen_step_sequencer example in arduino IDE but I get an error and it won't compile. The error is associated with line 12 in sampler.cpp, says that Adafruit_QSPI_GS25Q not found.

If I use the Sixteen_step_seq.uf2 file from the learning system it works (but obviously I can't access the code).

I took a copy of the latest example code from github but I have the same issue when I try to compile.

I have installed the libraries all the libraries stated here: https://learn.adafruit.com/adafruit-neotrellis-m4?view=all

What am I missing?

Many thanks

**Comment by ladyada** [comment]
hiya we refactored the QSPI interface (for the better) an forgot to update this library. its fixed now, please tr it :)

**Comment by wurls80** [comment]
Hi

Thanks. That seems to  have cleared that issue, but have now got another.

multiple libraries were found for "Adafruit_ZeroDMA.h

and
In file included from sketch/record.cpp:10:0:
...../Arduino/libraries/Adafruit_SPIFlash/src/Adafruit_SPIFlash.h:35:19: fata; error: SdFat.h: No such file or directory
 #include "SdFat.h"

Think the top one is my issue, not sure about the bottom one? I have version 3.1.1 of the Adafruit SPIFlash library installed, and I'm not being shown the option to update it.

Any clues again?

Many thanks

**Comment by ladyada** [comment]
yes check this page for the sdfat lirbary install info
https://learn.adafruit.com/adafruit-neotrellis-m4/arduino-libraries

**Comment by wurls80** [comment]
Thanks for the quick response!

I've done that, but then got to the next error:
......./Arduino/libraries/Audio-master/play_qspi_wav.h:9:37: fatal error: Adafruit_SPIFlash_FatFs.h: No such file or directory
 #include <Adafruit_SPIFlash_FatFs.h>

I deleted the Audio Master library files from my machine and re-installed it from a fresh download of the zip.

I then got an error related to the "Adafruit_ZeroI2S" library not being found. I installed that library through manage libraries..... having restarted the Arduino IDE it now compiles!! Thank you!!

**Comment by ladyada** [comment]
great!
