### ISSUE TITLE
NeoTreliis and esp32 ...

### ISSUE THREAD

**Issue by eqcq** [adafruit/Adafruit_NeoTrellisM4#25]
Hi there, I'm trying using the trellis m4 library with my esp32 dev kit board. 
Arduino put the library in the incomptabible list of library for all the esp32 boards ...
Have you a solution for this issue please ?

Thx a lot.

- Arduino board:  ESP32 Dev kit
- Arduino IDE version : the last one for osx

**Comment by ladyada** [comment]
this is the wrong library - follow
https://learn.adafruit.com/adafruit-neotrellis/arduino-code

**Comment by eqcq** [comment]
Thanks a lot !
