### ISSUE TITLE
How to configure Trellis M4 as a HID?

### ISSUE THREAD

**Issue by Did-13003** [adafruit/Adafruit_NeoTrellisM4#27]
Hello,

I'm looking to a library allowing to configure NeoTrellis M4 as a HID and especially as a joystick if possible 

Thank you very much if you can help me.

**Comment by ladyada** [comment]
you can compile Arduino in TinyUSB support mode and then use
https://github.com/adafruit/Adafruit_TinyUSB_Arduino/tree/master/examples/HID
for tech support post in the forums, thanx!

**Comment by Did-13003** [comment]
Thank you for your support!Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : ladyada <notifications@github.com> Date : 16/11/2020  21:14  (GMT+01:00) À : adafruit/Adafruit_NeoTrellisM4 <Adafruit_NeoTrellisM4@noreply.github.com> Cc : Did-13003 <jb.did@sfr.fr>, Author <author@noreply.github.com> Objet : Re: [adafruit/Adafruit_NeoTrellisM4] How to configure Trellis M4 as a
  HID? (#27) 
you can compile Arduino in TinyUSB support mode and then use
https://github.com/adafruit/Adafruit_TinyUSB_Arduino/tree/master/examples/HID
for tech support post in the forums, thanx!
