### ISSUE TITLE
Wrong NEO_PIN number 

### ISSUE THREAD

**Issue by GOPINATH-GS4** [adafruit/Adafruit_NeoTrellisM4#4]
I think the NEO_PIN number is incorrect in trellis_flash_sampler example
it is defined as 
**#define NEO_PIN 11**

shouldn't it be 
**#define NEO_PIN 10**
I changed to 10 and it works, let me know if I can make a pull request and fix it

**Comment by ladyada** [comment]
oops yes it should be, thats from some older hardware - please make a PR and we'll check it :)

**Comment by ladyada** [comment]
thax!
